version: "3.4"

services:
  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgisdata:/var/lib/postgresql/data
volumes:
  postgisdata:
