version: "3.4"

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - postgisdata:/var/lib/postgresql/data
volumes:
  postgisdata:
