version: "3.8"

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "admin_123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlvolume:/var/opt/mssql
volumes:
  mssqlvolume:
